export const cities = {
  status: "OK",
  result: {
    offset: 0,
    limit: 50,
    total: 261,
    webcams: [
      {
        id: "1518409586",
        status: "active",
        title: "Juiz de Fora: Rua Benjamin Constant - Juiz De Fora",
        location: {
          city: "Juiz de Fora",
          region: "Minas Gerais",
          region_code: "BR.15",
          country: "Brazil",
          country_code: "BR",
          continent: "South America",
          continent_code: "SA",
          latitude: -21.754029,
          longitude: -43.346869,
          timezone: "America/Sao_Paulo",
          wikipedia: "https://pt.wikipedia.org/wiki/Juiz de Fora",
        },
      },
      {
        id: "1227972392",
        status: "active",
        title: "St. Gallen › East: Klosterplatz",
        location: {
          city: "St. Gallen",
          region: "Canton of St. Gallen",
          region_code: "CH.SG",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 47.423397,
          longitude: 9.375914,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/St. Gallen",
        },
      },
      {
        id: "1289303006",
        status: "active",
        title: "Trikala",
        location: {
          city: "Trikala",
          region: "Thessaly - Central Greece",
          region_code: "GR.ESYE24",
          country: "Greece",
          country_code: "GR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 39.557464,
          longitude: 21.762457,
          timezone: "Europe/Athens",
          wikipedia: "https://en.wikipedia.org/wiki/Trikala",
        },
      },
      {
        id: "1179853135",
        status: "active",
        title: "Syd: Sydney - Sydney Opera House - Sydney Harbour Bridge",
        location: {
          city: "Syd",
          region: "New South Wales",
          region_code: "AU.02",
          country: "Australia",
          country_code: "AU",
          continent: "Oceania",
          continent_code: "OC",
          latitude: -33.864857,
          longitude: 151.208782,
          timezone: "Australia/Sydney",
          wikipedia: "https://en.wikipedia.org/wiki/Sydney",
        },
      },
      {
        id: "1252749312",
        status: "active",
        title: "Sille: hacıveyiszade cami",
        location: {
          city: "Sille",
          region: "Konya",
          region_code: "TR.71",
          country: "Turkey",
          country_code: "TR",
          continent: "Asia",
          continent_code: "AS",
          latitude: 37.876319,
          longitude: 32.48881,
          timezone: "Europe/Istanbul",
          wikipedia: "https://tr.wikipedia.org/wiki/Sille",
        },
      },
      {
        id: "1448989422",
        status: "active",
        title: "Minden: Markt",
        location: {
          city: "Minden",
          region: "North Rhine-Westphalia",
          region_code: "DE.07",
          country: "Germany",
          country_code: "DE",
          continent: "Europe",
          continent_code: "EU",
          latitude: 52.288146,
          longitude: 8.916693,
          timezone: "Europe/Berlin",
          wikipedia: "https://de.wikipedia.org/wiki/Minden",
        },
      },
      {
        id: "1494608365",
        status: "active",
        title:
          "Oludeniz: Belcekiz Beach Club - Ölüdeniz Plajı - Belcekiz Beach Hotel - Paragliding Oludeniz Turkey - Ölüdeniz - Murat iletişim Bilgisayar ve güvenlik sistemleri Türk Telekom, İnternet, KAREL - PARADOX - HP - Fethiye",
        location: {
          city: "Oludeniz",
          region: "Muğla",
          region_code: "TR.48",
          country: "Turkey",
          country_code: "TR",
          continent: "Asia",
          continent_code: "AS",
          latitude: 36.545979,
          longitude: 29.123582,
          timezone: "Europe/Istanbul",
          wikipedia: "",
        },
      },
      {
        id: "1460602673",
        status: "active",
        title: "Shinjuku",
        location: {
          city: "Shinjuku",
          region: "Tokyo",
          region_code: "KWDghWeD",
          country: "Japan",
          country_code: "JP",
          continent: "Asia",
          continent_code: "AS",
          latitude: 35.692215,
          longitude: 139.702266,
          timezone: "Asia/Tokyo",
          wikipedia: "https://ja.wikipedia.org/wiki/新宿区",
        },
      },
      {
        id: "1522082167",
        status: "active",
        title: "Recoleta › South-West: Santiago De Chile",
        location: {
          city: "Recoleta",
          region: "Santiago Metropolitan Region",
          region_code: "CL.12",
          country: "Chile",
          country_code: "CL",
          continent: "South America",
          continent_code: "SA",
          latitude: -33.42363,
          longitude: -70.63402,
          timezone: "America/Santiago",
          wikipedia: "https://es.wikipedia.org/wiki/Recoleta (Chile)",
        },
      },
      {
        id: "1503586256",
        status: "active",
        title: "District of Prievidza › North-West: Čavoj - Temešská rock",
        location: {
          city: "District of Prievidza",
          region: "Region of Trenčín",
          region_code: "SK.06",
          country: "Slovakia",
          country_code: "SK",
          continent: "Europe",
          continent_code: "EU",
          latitude: 48.885241,
          longitude: 18.502339,
          timezone: "Europe/Bratislava",
          wikipedia: "https://sk.wikipedia.org/wiki/Prievidza (okres)",
        },
      },
      {
        id: "1302959392",
        status: "active",
        title: "Appenzell: Dorf",
        location: {
          city: "Appenzell",
          region: "Appenzell Inner Rhodes",
          region_code: "CH.AI",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 47.330723,
          longitude: 9.408588,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Appenzell (Bezirk)",
        },
      },
      {
        id: "1263629371",
        status: "active",
        title: "Buftea: parc otopeni",
        location: {
          city: "Buftea",
          region: "Ilfov",
          region_code: "Kehjjccj",
          country: "Romania",
          country_code: "RO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 44.550268,
          longitude: 26.072147,
          timezone: "Europe/Bucharest",
          wikipedia: "",
        },
      },
      {
        id: "1450819737",
        status: "active",
        title: "l'Ametlla de Mar › North-East: L'Ametlla de Mar",
        location: {
          city: "l'Ametlla de Mar",
          region: "Catalonia",
          region_code: "ES.56",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 40.883262,
          longitude: 0.805172,
          timezone: "Europe/Madrid",
          wikipedia: "https://ca.wikipedia.org/wiki/L'Ametlla de Mar",
        },
      },
      {
        id: "1501370730",
        status: "active",
        title: "Durango Ciudad: Ciudad Industrial",
        location: {
          city: "Durango Ciudad",
          region: "Durango",
          region_code: "MX.10",
          country: "Mexico",
          country_code: "MX",
          continent: "North America",
          continent_code: "NA",
          latitude: 24.01104,
          longitude: -104.668808,
          timezone: "America/Monterrey",
          wikipedia: "",
        },
      },
      {
        id: "1448811166",
        status: "active",
        title: "Barcelona: Sagrada Família - La Sagrada Familia",
        location: {
          city: "Barcelona",
          region: "Catalonia",
          region_code: "ES.56",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 41.40369,
          longitude: 2.17433,
          timezone: "Europe/Madrid",
          wikipedia: "https://ca.wikipedia.org/wiki/Barcelona",
        },
      },
      {
        id: "1445291011",
        status: "active",
        title: "Turnov › North: náměstí Českého Ráje",
        location: {
          city: "Turnov",
          region: "Northeast",
          region_code: "CZ.83",
          country: "Czechia",
          country_code: "CZ",
          continent: "Europe",
          continent_code: "EU",
          latitude: 50.586983,
          longitude: 15.157273,
          timezone: "Europe/Prague",
          wikipedia: "https://cs.wikipedia.org/wiki/Turnov",
        },
      },
      {
        id: "1492767276",
        status: "active",
        title: "Ústí nad Labem: Ústí nad Labem-centrum",
        location: {
          city: "Ústí nad Labem",
          region: "Northwest",
          region_code: "CZ.81",
          country: "Czechia",
          country_code: "CZ",
          continent: "Europe",
          continent_code: "EU",
          latitude: 50.655245,
          longitude: 14.03978,
          timezone: "Europe/Prague",
          wikipedia: "https://cs.wikipedia.org/wiki/Ústí nad Labem",
        },
      },
      {
        id: "1524781982",
        status: "active",
        title: "Santiago: de - Metropolitana",
        location: {
          city: "Santiago",
          region: "Santiago Metropolitan Region",
          region_code: "CL.12",
          country: "Chile",
          country_code: "CL",
          continent: "South America",
          continent_code: "SA",
          latitude: -33.423421,
          longitude: -70.633507,
          timezone: "America/Santiago",
          wikipedia: "https://es.wikipedia.org/wiki/Santiago (comuna)",
        },
      },
      {
        id: "1516793823",
        status: "active",
        title:
          "Cape Town › South: Bo-Kaap - Tamboerskloof - Gardens - Oranjezicht - Lion's Head - Table Mountain",
        location: {
          city: "Cape Town",
          region: "Western Cape",
          region_code: "ZA.11",
          country: "South Africa",
          country_code: "ZA",
          continent: "Africa",
          continent_code: "AF",
          latitude: -33.923962,
          longitude: 18.414224,
          timezone: "Africa/Johannesburg",
          wikipedia: "https://en.wikipedia.org/wiki/Cape Town",
        },
      },
      {
        id: "1383589802",
        status: "active",
        title: "Andenes: Panorama",
        location: {
          city: "Andenes",
          region: "Nordland",
          region_code: "KgIbWID",
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 69.324001,
          longitude: 16.115924,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1453251984",
        status: "active",
        title: "Yuzhno-Sakhalinsk › West: Lenin Square",
        location: {
          city: "Yuzhno-Sakhalinsk",
          region: "Sakhalin Oblast",
          region_code: "RU.64",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.957813,
          longitude: 142.730545,
          timezone: "Asia/Sakhalin",
          wikipedia: "",
        },
      },
      {
        id: "1470352298",
        status: "active",
        title: "Unije: Otok - Primorsko-Goranska",
        location: {
          city: "Unije",
          region: "Primorje-Gorski Kotar County",
          region_code: "HR.12",
          country: "Croatia",
          country_code: "HR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 44.636682,
          longitude: 14.24738,
          timezone: "Europe/Zagreb",
          wikipedia: "",
        },
      },
      {
        id: "1515276669",
        status: "active",
        title: "unknown: Vorkuta - Pl. Mira, Russia",
        location: {
          city: "unknown",
          region: null,
          region_code: null,
          country: "unknown",
          country_code: "XX",
          continent: "unknown",
          continent_code: "XX",
          latitude: 67.493738,
          longitude: 64.050502,
          timezone: "Europe/London",
          wikipedia: "",
        },
      },
      {
        id: "1399837432",
        status: "active",
        title: "Sarajevo",
        location: {
          city: "Sarajevo",
          region: "Federation of Bosnia and Herzegovina",
          region_code: "BA.01",
          country: "Bosnia and Herzegovina",
          country_code: "BA",
          continent: "Europe",
          continent_code: "EU",
          latitude: 43.856414,
          longitude: 18.402886,
          timezone: "Europe/Sarajevo",
          wikipedia: "https://sh.wikipedia.org/wiki/Sarajevo",
        },
      },
      {
        id: "1246977254",
        status: "active",
        title: "Białystok: Sienkiewicza/Jurowiecka Street",
        location: {
          city: "Białystok",
          region: "Podlaskie Voivodeship",
          region_code: "PL.81",
          country: "Poland",
          country_code: "PL",
          continent: "Europe",
          continent_code: "EU",
          latitude: 53.136396,
          longitude: 23.165317,
          timezone: "Europe/Warsaw",
          wikipedia: "https://pl.wikipedia.org/wiki/Białystok",
        },
      },
      {
        id: "1473687913",
        status: "active",
        title: "Kiyokawa: village office",
        location: {
          city: "Kiyokawa",
          region: "Kanagawa Prefecture",
          region_code: "Kejbcgbu",
          country: "Japan",
          country_code: "JP",
          continent: "Asia",
          continent_code: "AS",
          latitude: 35.482374,
          longitude: 139.276434,
          timezone: "Asia/Tokyo",
          wikipedia: "https://ja.wikipedia.org/wiki/清川村",
        },
      },
      {
        id: "1449975078",
        status: "active",
        title:
          "Ussurijsk: Уссурийск - Приморский край, Россия: Уссурийск. Садовая а Вид на кольцо ул.Садовая и просп.Блюхера",
        location: {
          city: "Ussurijsk",
          region: "Primorsky Krai",
          region_code: "RU.59",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 43.812135,
          longitude: 131.979039,
          timezone: "Asia/Vladivostok",
          wikipedia: "",
        },
      },
      {
        id: "1567524928",
        status: "active",
        title: "Port St. Lucie: Saint Lucie West",
        location: {
          city: "Port St. Lucie",
          region: "Florida",
          region_code: "US.FL",
          country: "United States",
          country_code: "US",
          continent: "North America",
          continent_code: "NA",
          latitude: 27.168711,
          longitude: -80.151564,
          timezone: "America/New_York",
          wikipedia: "https://en.wikipedia.org/wiki/Port St. Lucie, Florida",
        },
      },
      {
        id: "1410728612",
        status: "active",
        title: "Toronto: High Park Village",
        location: {
          city: "Toronto",
          region: "Ontario",
          region_code: "CA.08",
          country: "Canada",
          country_code: "CA",
          continent: "North America",
          continent_code: "NA",
          latitude: 43.656717,
          longitude: -79.464358,
          timezone: "America/Toronto",
          wikipedia: "https://en.wikipedia.org/wiki/Toronto",
        },
      },
      {
        id: "1497776708",
        status: "active",
        title: "Iasi: Unirea Hotel & Spa",
        location: {
          city: "Iasi",
          region: "Iasi",
          region_code: "KeeDjugu",
          country: "Romania",
          country_code: "RO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 47.16667,
          longitude: 27.6,
          timezone: "Europe/Bucharest",
          wikipedia: "",
        },
      },
      {
        id: "1444993841",
        status: "active",
        title: "Kaluga › East: Ulitsa Kirova",
        location: {
          city: "Kaluga",
          region: "Kaluga Oblast",
          region_code: "RU.25",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 54.515427,
          longitude: 36.247954,
          timezone: "Europe/Moscow",
          wikipedia: "",
        },
      },
      {
        id: "1473374057",
        status: "active",
        title: "Venice: Rialto Bridge",
        location: {
          city: "Venice",
          region: "Veneto",
          region_code: "IT.20",
          country: "Italy",
          country_code: "IT",
          continent: "Europe",
          continent_code: "EU",
          latitude: 45.43723,
          longitude: 12.335206,
          timezone: "Europe/Rome",
          wikipedia: "https://it.wikipedia.org/wiki/Venezia",
        },
      },
      {
        id: "1287165646",
        status: "active",
        title: "Saluzzo: corso",
        location: {
          city: "Saluzzo",
          region: "Piemont",
          region_code: "IT.12",
          country: "Italy",
          country_code: "IT",
          continent: "Europe",
          continent_code: "EU",
          latitude: 44.645296,
          longitude: 7.491485,
          timezone: "Europe/Rome",
          wikipedia: "https://it.wikipedia.org/wiki/Saluzzo",
        },
      },
      {
        id: "1587453076",
        status: "active",
        title: "Moscow › South-East: Raspletina St",
        location: {
          city: "Moscow",
          region: "Moscow",
          region_code: "RU.48",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 55.789906,
          longitude: 37.479759,
          timezone: "Europe/Moscow",
          wikipedia: "",
        },
      },
      {
        id: "1503353468",
        status: "active",
        title: "Syd: Circular quay",
        location: {
          city: "Syd",
          region: "New South Wales",
          region_code: "AU.02",
          country: "Australia",
          country_code: "AU",
          continent: "Oceania",
          continent_code: "OC",
          latitude: -33.861453,
          longitude: 151.211386,
          timezone: "Australia/Sydney",
          wikipedia: "https://en.wikipedia.org/wiki/Sydney",
        },
      },
      {
        id: "1212847240",
        status: "active",
        title: "Beaucourt: Live Cam",
        location: {
          city: "Beaucourt",
          region: "Bourgogne-Franche-Comte",
          region_code: "FR.27",
          country: "France",
          country_code: "FR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 47.484637,
          longitude: 6.927034,
          timezone: "Europe/Paris",
          wikipedia: "https://fr.wikipedia.org/wiki/Beaucourt",
        },
      },
      {
        id: "1385106644",
        status: "active",
        title: "Chur › West: Altstadt",
        location: {
          city: "Chur",
          region: "Grisons",
          region_code: "CH.GR",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.846101,
          longitude: 9.533976,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Chur",
        },
      },
      {
        id: "1541698349",
        status: "active",
        title:
          "ˈpæɹ.ɪs: 16th arrondissement - Bois de Boulogne - Paris La Défense - Paris",
        location: {
          city: "ˈpæɹ.ɪs",
          region: "Ile-de-France",
          region_code: "FR.11",
          country: "France",
          country_code: "FR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 48.867189,
          longitude: 2.272416,
          timezone: "Europe/Paris",
          wikipedia: "https://fr.wikipedia.org/wiki/Paris",
        },
      },
      {
        id: "1498623060",
        status: "active",
        title: "Trzebinia: Market square",
        location: {
          city: "Trzebinia",
          region: "Lesser Poland Voivodeship",
          region_code: "PL.77",
          country: "Poland",
          country_code: "PL",
          continent: "Europe",
          continent_code: "EU",
          latitude: 50.159697,
          longitude: 19.471335,
          timezone: "Europe/Warsaw",
          wikipedia: "https://pl.wikipedia.org/wiki/Trzebinia",
        },
      },
      {
        id: "1456874522",
        status: "active",
        title: "Vladivostok › South-East: Pos'etskaya Vladi",
        location: {
          city: "Vladivostok",
          region: "Primorsky Krai",
          region_code: "RU.59",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 43.112098,
          longitude: 131.879475,
          timezone: "Asia/Vladivostok",
          wikipedia: "https://ru.wikipedia.org/wiki/Владивосток",
        },
      },
      {
        id: "1520450745",
        status: "active",
        title: "Yaiza › North-East: Marina Lanzarote - Puerto de Lanzarote",
        location: {
          city: "Yaiza",
          region: "Canary Islands",
          region_code: "ES.53",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 28.96443,
          longitude: -13.537002,
          timezone: "Atlantic/Canary",
          wikipedia: "https://es.wikipedia.org/wiki/Yaiza",
        },
      },
      {
        id: "1542185753",
        status: "active",
        title: "Verkhnyaya Inta › North: Инта - Коми, Россия",
        location: {
          city: "Verkhnyaya Inta",
          region: "Komi Republic",
          region_code: "RU.34",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 66.036753,
          longitude: 60.115675,
          timezone: "Europe/Moscow",
          wikipedia: "https://ru.wikipedia.org/wiki/Верхняя Инта",
        },
      },
      {
        id: "1436618683",
        status: "active",
        title: "Chernihiv › East",
        location: {
          city: "Chernihiv",
          region: "Chernihiv Oblast",
          region_code: "UA.02",
          country: "Ukraine",
          country_code: "UA",
          continent: "Europe",
          continent_code: "EU",
          latitude: 51.498795,
          longitude: 31.276118,
          timezone: "Europe/Kiev",
          wikipedia: "https://uk.wikipedia.org/wiki/Чернігів",
        },
      },
      {
        id: "1455450726",
        status: "active",
        title: "Jastrzębie Zdrój › West",
        location: {
          city: "Jastrzębie Zdrój",
          region: "Silesian Voivodeship",
          region_code: "PL.83",
          country: "Poland",
          country_code: "PL",
          continent: "Europe",
          continent_code: "EU",
          latitude: 49.952803,
          longitude: 18.611655,
          timezone: "Europe/Warsaw",
          wikipedia: "https://pl.wikipedia.org/wiki/Jastrzębie-Zdrój",
        },
      },
      {
        id: "1241895553",
        status: "active",
        title: "Kinsarvik › West: › West: Hordaland",
        location: {
          city: "Kinsarvik",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 60.37567,
          longitude: 6.71948,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1575445569",
        status: "active",
        title: "Palamós: Port de Palamós",
        location: {
          city: "Palamós",
          region: "Catalonia",
          region_code: "ES.56",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 41.845011,
          longitude: 3.126426,
          timezone: "Europe/Madrid",
          wikipedia: "https://es.wikipedia.org/wiki/Palamós",
        },
      },
      {
        id: "1451443190",
        status: "active",
        title: "городское поселение Углич: Углич - Ярославская область, Россия",
        location: {
          city: "городское поселение Углич",
          region: "Yaroslavl Oblast",
          region_code: "RU.88",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 57.526012,
          longitude: 38.318574,
          timezone: "Europe/Moscow",
          wikipedia: "https://ru.wikipedia.org/wiki/Углич",
        },
      },
      {
        id: "1379691005",
        status: "active",
        title:
          "Sopot › North-East: Plac Przyjaciół Sopotu - Bohaterów Monte Cassino",
        location: {
          city: "Sopot",
          region: "Pomeranian Voivodeship",
          region_code: "PL.82",
          country: "Poland",
          country_code: "PL",
          continent: "Europe",
          continent_code: "EU",
          latitude: 54.444902,
          longitude: 18.568209,
          timezone: "Europe/Warsaw",
          wikipedia: "https://pl.wikipedia.org/wiki/Sopot",
        },
      },
      {
        id: "1560236422",
        status: "active",
        title: "Guardo: Castille and León",
        location: {
          city: "Guardo",
          region: "Castile and León",
          region_code: "ES.55",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 42.789783,
          longitude: -4.844643,
          timezone: "Europe/Madrid",
          wikipedia: "https://es.wikipedia.org/wiki/Guardo",
        },
      },
      {
        id: "1454143038",
        status: "active",
        title: "Duart › West: Isle of Mull",
        location: {
          city: "Duart",
          region: "Scotland",
          region_code: "GB.SCT",
          country: "United Kingdom",
          country_code: "GB",
          continent: "Europe",
          continent_code: "EU",
          latitude: 56.4635,
          longitude: -5.39967,
          timezone: "Europe/London",
          wikipedia: "",
        },
      },
    ],
  },
};
