export const forests = {
	status: "OK",
	result: {
		offset: 0,
		limit: 50,
		total: 15,
		webcams: [
			{
				id: "1507849714",
				status: "active",
				title: "Big Sky › West: Everett's 8800",
				location: {
					city: "Big Sky",
					region: "Montana",
					region_code: "US.MT",
					country: "United States",
					country_code: "US",
					continent: "North America",
					continent_code: "NA",
					latitude: 45.27242,
					longitude: -111.395005,
					timezone: "America/Denver",
					wikipedia: "https://en.wikipedia.org/wiki/Big Sky, Montana",
				},
			},
			{
				id: "1518864462",
				status: "active",
				title: "Castelo › South: Rampa de Voo Livre",
				location: {
					city: "Castelo",
					region: "Espírito Santo",
					region_code: "BR.08",
					country: "Brazil",
					country_code: "BR",
					continent: "South America",
					continent_code: "SA",
					latitude: -20.587709,
					longitude: -41.165751,
					timezone: "America/Sao_Paulo",
					wikipedia: "https://pt.wikipedia.org/wiki/Castelo (Espírito Santo)",
				},
			},
			{
				id: "1510010427",
				status: "active",
				title: "Trieste: Università degli Studi di Trieste",
				location: {
					city: "Trieste",
					region: "Friuli Venezia Giulia",
					region_code: "IT.06",
					country: "Italy",
					country_code: "IT",
					continent: "Europe",
					continent_code: "EU",
					latitude: 45.659195,
					longitude: 13.794006,
					timezone: "Europe/Rome",
					wikipedia: "https://it.wikipedia.org/wiki/Trieste",
				},
			},
			{
				id: "1513599391",
				status: "active",
				title: "Zona 18: Vista Hermosa",
				location: {
					city: "Zona 18",
					region: "Guatemala",
					region_code: "GT.07",
					country: "Guatemala",
					country_code: "GT",
					continent: "North America",
					continent_code: "NA",
					latitude: 14.602791,
					longitude: -90.468786,
					timezone: "America/Guatemala",
					wikipedia: "",
				},
			},
			{
				id: "1576031738",
				status: "active",
				title: "Vass › East: Fly Rod Lake",
				location: {
					city: "Vass",
					region: "North Carolina",
					region_code: "US.NC",
					country: "United States",
					country_code: "US",
					continent: "North America",
					continent_code: "NA",
					latitude: 35.259436,
					longitude: -79.392987,
					timezone: "America/New_York",
					wikipedia: "https://en.wikipedia.org/wiki/Vass, North Carolina",
				},
			},
			{
				id: "1509487480",
				status: "active",
				title: "District of Nové Mesto nad Váhom › South-East: Inovec - Inovec Považský - Povazsky Inovec",
				location: {
					city: "District of Nové Mesto nad Váhom",
					region: "Region of Trenčín",
					region_code: "SK.06",
					country: "Slovakia",
					country_code: "SK",
					continent: "Europe",
					continent_code: "EU",
					latitude: 48.774713,
					longitude: 18.041825,
					timezone: "Europe/Bratislava",
					wikipedia: "https://sk.wikipedia.org/wiki/Nové Mesto nad Váhom (okres)",
				},
			},
			{
				id: "1511971281",
				status: "active",
				title: "Harghita-Bai: Harghita",
				location: {
					city: "Harghita-Bai",
					region: "Harghita",
					region_code: "KeegbjjI",
					country: "Romania",
					country_code: "RO",
					continent: "Europe",
					continent_code: "EU",
					latitude: 46.38442,
					longitude: 25.644675,
					timezone: "Europe/Bucharest",
					wikipedia: "https://ro.wikipedia.org/wiki/Harghita-Băi, Harghita",
				},
			},
			{
				id: "1575703473",
				status: "active",
				title: "Peypin › North-East: Montagne Sainte-Victoire",
				location: {
					city: "Peypin",
					region: "Provence-Alpes-Côte d'Azur",
					region_code: "FR.93",
					country: "France",
					country_code: "FR",
					continent: "Europe",
					continent_code: "EU",
					latitude: 43.392224,
					longitude: 5.550859,
					timezone: "Europe/Paris",
					wikipedia: "https://fr.wikipedia.org/wiki/Peypin",
				},
			},
			{
				id: "1431242331",
				status: "active",
				title: "Olesnice v Orlickych horach › West: SKI areál Hartman",
				location: {
					city: "Olesnice v Orlickych horach",
					region: "Northeast",
					region_code: "CZ.83",
					country: "Czechia",
					country_code: "CZ",
					continent: "Europe",
					continent_code: "EU",
					latitude: 50.377146,
					longitude: 16.31474,
					timezone: "Europe/Prague",
					wikipedia: "https://cs.wikipedia.org/wiki/Olešnice v Orlických horách",
				},
			},
			{
				id: "1521277619",
				status: "active",
				title: "Bonneval: Feissons-sur-Isère",
				location: {
					city: "Bonneval",
					region: "Auvergne-Rhone-Alpes",
					region_code: "FR.84",
					country: "France",
					country_code: "FR",
					continent: "Europe",
					continent_code: "EU",
					latitude: 45.498279,
					longitude: 6.429819,
					timezone: "Europe/Paris",
					wikipedia: "https://fr.wikipedia.org/wiki/Bonneval (Haute-Loire)",
				},
			},
			{
				id: "1583833787",
				status: "active",
				title: "Neuenburg",
				location: {
					city: "Neuenburg",
					region: "Baden-Württemberg",
					region_code: "DE.01",
					country: "Germany",
					country_code: "DE",
					continent: "Europe",
					continent_code: "EU",
					latitude: 48.852757,
					longitude: 8.587189,
					timezone: "Europe/Berlin",
					wikipedia: "https://de.wikipedia.org/wiki/Neuenbürg",
				},
			},
			{
				id: "1514886350",
				status: "active",
				title: "San Pedro Carcha: Departamento de Alta Verapaz - El Paraiso de América",
				location: {
					city: "San Pedro Carcha",
					region: "San Pedro Carcha",
					region_code: "",
					country: "Guatemala",
					country_code: "GT",
					continent: "North America",
					continent_code: "NA",
					latitude: 15.410982,
					longitude: -90.057678,
					timezone: "America/Guatemala",
					wikipedia: "",
				},
			},
			{
				id: "1507918705",
				status: "active",
				title: "St. Blasien › South-West: Rehbach",
				location: {
					city: "St. Blasien",
					region: "Baden-Württemberg",
					region_code: "DE.01",
					country: "Germany",
					country_code: "DE",
					continent: "Europe",
					continent_code: "EU",
					latitude: 47.811757,
					longitude: 8.066379,
					timezone: "Europe/Berlin",
					wikipedia: "https://de.wikipedia.org/wiki/St. Blasien",
				},
			},
			{
				id: "1517914988",
				status: "active",
				title: "Palazzuolo sul Senio: Toscana",
				location: {
					city: "Palazzuolo sul Senio",
					region: "Emilia-Romagna",
					region_code: "IT.05",
					country: "Italy",
					country_code: "IT",
					continent: "Europe",
					continent_code: "EU",
					latitude: 44.11298,
					longitude: 11.5427,
					timezone: "Europe/Rome",
					wikipedia: "https://it.wikipedia.org/wiki/Palazzuolo sul Senio",
				},
			},
			{
				id: "1581345124",
				status: "active",
				title: "Freiamt › South-West",
				location: {
					city: "Freiamt",
					region: "Baden-Württemberg",
					region_code: "DE.01",
					country: "Germany",
					country_code: "DE",
					continent: "Europe",
					continent_code: "EU",
					latitude: 48.204529,
					longitude: 7.971944,
					timezone: "Europe/Berlin",
					wikipedia: "https://de.wikipedia.org/wiki/Freiamt (Schwarzwald)",
				},
			},
		],
	},
};
