export const mountains = {
  status: "OK",
  result: {
    offset: 0,
    limit: 50,
    total: 130,
    webcams: [
      {
        id: "1235134756",
        status: "active",
        title: "Finse",
        location: {
          city: "Finse",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 60.601764,
          longitude: 7.504059,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1444648696",
        status: "active",
        title: "Haukeliseter › South-East: Haukeliseter Fjellstue",
        location: {
          city: "Haukeliseter",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 59.823811,
          longitude: 7.194037,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1503586256",
        status: "active",
        title: "District of Prievidza › North-West: Čavoj - Temešská rock",
        location: {
          city: "District of Prievidza",
          region: "Region of Trenčín",
          region_code: "SK.06",
          country: "Slovakia",
          country_code: "SK",
          continent: "Europe",
          continent_code: "EU",
          latitude: 48.885241,
          longitude: 18.502339,
          timezone: "Europe/Bratislava",
          wikipedia: "https://sk.wikipedia.org/wiki/Prievidza (okres)",
        },
      },
      {
        id: "1234951380",
        status: "active",
        title: "Diomede: Dateline Cam, Little",
        location: {
          city: "Diomede",
          region: "Alaska",
          region_code: "US.AK",
          country: "United States",
          country_code: "US",
          continent: "North America",
          continent_code: "NA",
          latitude: 65.758869,
          longitude: -168.951123,
          timezone: "America/Nome",
          wikipedia: "https://en.wikipedia.org/wiki/Diomede, Alaska",
        },
      },
      {
        id: "1516793823",
        status: "active",
        title:
          "Cape Town › South: Bo-Kaap - Tamboerskloof - Gardens - Oranjezicht - Lion's Head - Table Mountain",
        location: {
          city: "Cape Town",
          region: "Western Cape",
          region_code: "ZA.11",
          country: "South Africa",
          country_code: "ZA",
          continent: "Africa",
          continent_code: "AF",
          latitude: -33.923962,
          longitude: 18.414224,
          timezone: "Africa/Johannesburg",
          wikipedia: "https://en.wikipedia.org/wiki/Cape Town",
        },
      },
      {
        id: "1503612662",
        status: "active",
        title: "Hong Kong: The Peak",
        location: {
          city: "Hong Kong",
          region: null,
          region_code: null,
          country: "China",
          country_code: "CN",
          continent: "Asia",
          continent_code: "AS",
          latitude: 22.265465,
          longitude: 114.160741,
          timezone: "Asia/Hong_Kong",
          wikipedia: "https://zh.wikipedia.org/wiki/香港",
        },
      },
      {
        id: "1384854763",
        status: "active",
        title: "Sachseln: Sarnersee",
        location: {
          city: "Sachseln",
          region: "Canton of Obwalden",
          region_code: "CH.OW",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.873725,
          longitude: 8.244305,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Sachseln",
        },
      },
      {
        id: "1507849714",
        status: "active",
        title: "Big Sky › West: Everett's 8800",
        location: {
          city: "Big Sky",
          region: "Montana",
          region_code: "US.MT",
          country: "United States",
          country_code: "US",
          continent: "North America",
          continent_code: "NA",
          latitude: 45.27242,
          longitude: -111.395005,
          timezone: "America/Denver",
          wikipedia: "https://en.wikipedia.org/wiki/Big Sky, Montana",
        },
      },
      {
        id: "1419199968",
        status: "active",
        title: "Rjukan › South: Gaustablikk Høyfjellshotell AS",
        location: {
          city: "Rjukan",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 59.8805,
          longitude: 8.73739,
          timezone: "Europe/Oslo",
          wikipedia: "https://en.wikipedia.org/wiki/Rjukan",
        },
      },
      {
        id: "1385106644",
        status: "active",
        title: "Chur › West: Altstadt",
        location: {
          city: "Chur",
          region: "Grisons",
          region_code: "CH.GR",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.846101,
          longitude: 9.533976,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Chur",
        },
      },
      {
        id: "1539770011",
        status: "active",
        title: "Cheia › South-East: Gropsoarele Peak",
        location: {
          city: "Cheia",
          region: "Prahova",
          region_code: "KehDDDIu",
          country: "Romania",
          country_code: "RO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 45.48983,
          longitude: 25.97532,
          timezone: "Europe/Bucharest",
          wikipedia: "",
        },
      },
      {
        id: "1343381445",
        status: "active",
        title: "Ennetburgen: Hotel Villa Honegg",
        location: {
          city: "Ennetburgen",
          region: "Canton of Nidwalden",
          region_code: "CH.NW",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.995124,
          longitude: 8.403082,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Ennetbürgen",
        },
      },
      {
        id: "1349961615",
        status: "active",
        title: "Reichenbach im Kandertal: Flugplatz Reichenbach",
        location: {
          city: "Reichenbach im Kandertal",
          region: "Bern",
          region_code: "CH.BE",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.613743,
          longitude: 7.678757,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Reichenbach im Kandertal",
        },
      },
      {
        id: "1302607195",
        status: "active",
        title: "Ennetburgen: Flugplatz Buochs LSZC richtung west Pilatus",
        location: {
          city: "Ennetburgen",
          region: "Canton of Nidwalden",
          region_code: "CH.NW",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.971702,
          longitude: 8.401794,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Ennetbürgen",
        },
      },
      {
        id: "1451736699",
        status: "active",
        title: "Horni Lhota: Česko",
        location: {
          city: "Horni Lhota",
          region: "Central Moravia",
          region_code: "CZ.84",
          country: "Czechia",
          country_code: "CZ",
          continent: "Europe",
          continent_code: "EU",
          latitude: 49.857137,
          longitude: 18.056599,
          timezone: "Europe/Prague",
          wikipedia: "https://cs.wikipedia.org/wiki/Horní Lhota (okres Zlín)",
        },
      },
      {
        id: "1241895553",
        status: "active",
        title: "Kinsarvik › West: › West: Hordaland",
        location: {
          city: "Kinsarvik",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 60.37567,
          longitude: 6.71948,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1575445569",
        status: "active",
        title: "Palamós: Port de Palamós",
        location: {
          city: "Palamós",
          region: "Catalonia",
          region_code: "ES.56",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 41.845011,
          longitude: 3.126426,
          timezone: "Europe/Madrid",
          wikipedia: "https://es.wikipedia.org/wiki/Palamós",
        },
      },
      {
        id: "1466404911",
        status: "active",
        title:
          "Southern Region › South: Kerlingarfjöll - South - Kerlingarfjöll Mountain resort, mt. Mæn",
        location: {
          city: "Southern Region",
          region: null,
          region_code: null,
          country: "Iceland",
          country_code: "IS",
          continent: "Europe",
          continent_code: "EU",
          latitude: 64.684788,
          longitude: -19.320732,
          timezone: "Atlantic/Reykjavik",
          wikipedia: "",
        },
      },
      {
        id: "1514969050",
        status: "active",
        title: "Bivio: Bivio Sportanlagen AG",
        location: {
          city: "Bivio",
          region: "Grisons",
          region_code: "CH.GR",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.452453,
          longitude: 9.640795,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Bivio",
        },
      },
      {
        id: "1518864462",
        status: "active",
        title: "Castelo › South: Rampa de Voo Livre",
        location: {
          city: "Castelo",
          region: "Espírito Santo",
          region_code: "BR.08",
          country: "Brazil",
          country_code: "BR",
          continent: "South America",
          continent_code: "SA",
          latitude: -20.587709,
          longitude: -41.165751,
          timezone: "America/Sao_Paulo",
          wikipedia: "https://pt.wikipedia.org/wiki/Castelo (Espírito Santo)",
        },
      },
      {
        id: "1180633999",
        status: "active",
        title: "Lake Tekapo",
        location: {
          city: "Lake Tekapo",
          region: "Canterbury",
          region_code: "NZ.E9",
          country: "New Zealand",
          country_code: "NZ",
          continent: "Oceania",
          continent_code: "OC",
          latitude: -44.006645,
          longitude: 170.486698,
          timezone: "Pacific/Auckland",
          wikipedia: "",
        },
      },
      {
        id: "1299745209",
        status: "active",
        title: "Anykščiai: Kalita hill (toboggan run)",
        location: {
          city: "Anykščiai",
          region: "Utena County",
          region_code: "LT.64",
          country: "Lithuania",
          country_code: "LT",
          continent: "Europe",
          continent_code: "EU",
          latitude: 55.526189,
          longitude: 25.123758,
          timezone: "Europe/Vilnius",
          wikipedia: "https://lt.wikipedia.org/wiki/Anykščiai",
        },
      },
      {
        id: "1517650191",
        status: "active",
        title: "Wald-Michelbach: Siedelsbrunn",
        location: {
          city: "Wald-Michelbach",
          region: "Hesse",
          region_code: "DE.05",
          country: "Germany",
          country_code: "DE",
          continent: "Europe",
          continent_code: "EU",
          latitude: 49.550468,
          longitude: 8.813138,
          timezone: "Europe/Berlin",
          wikipedia: "https://de.wikipedia.org/wiki/Wald-Michelbach",
        },
      },
      {
        id: "1547119085",
        status: "active",
        title: "Kyrkjebygda › South-West: Kyrkjebygdheia: Kyrkjebygdheia",
        location: {
          city: "Kyrkjebygda",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 59.175491,
          longitude: 8.577316,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1450782090",
        status: "active",
        title: "unknown › South-East: Sønstevatn - Imingfjellet",
        location: {
          city: "unknown",
          region: null,
          region_code: null,
          country: "unknown",
          country_code: "XX",
          continent: "unknown",
          continent_code: "XX",
          latitude: 60.238681,
          longitude: 8.574715,
          timezone: "Europe/London",
          wikipedia: "",
        },
      },
      {
        id: "1452358069",
        status: "active",
        title: "Rauland: Rauland Skisenter",
        location: {
          city: "Rauland",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 59.72212,
          longitude: 8.129389,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1010908662",
        status: "active",
        title: "Grindelwald: First - LIVE ( m.ü.M)",
        location: {
          city: "Grindelwald",
          region: "Bern",
          region_code: "CH.BE",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.658627,
          longitude: 8.055725,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Grindelwald",
        },
      },
      {
        id: "1453252173",
        status: "active",
        title: "Yuzhno-Sakhalinsk › East: Leni",
        location: {
          city: "Yuzhno-Sakhalinsk",
          region: "Sakhalin Oblast",
          region_code: "RU.64",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.955678,
          longitude: 142.781206,
          timezone: "Asia/Sakhalin",
          wikipedia: "",
        },
      },
      {
        id: "1551588161",
        status: "active",
        title:
          "Julian › South: 15574 N Peak Rd - Julian Cabins - Lake Cuyamaca",
        location: {
          city: "Julian",
          region: "California",
          region_code: "US.CA",
          country: "United States",
          country_code: "US",
          continent: "North America",
          continent_code: "NA",
          latitude: 33.07866,
          longitude: -116.60196,
          timezone: "America/Los_Angeles",
          wikipedia: "",
        },
      },
      {
        id: "1226929566",
        status: "active",
        title:
          "Talloires-Montmin: Baie de Talloires - Talloires - Lake Annecy - Annecy",
        location: {
          city: "Talloires-Montmin",
          region: "Auvergne-Rhone-Alpes",
          region_code: "FR.84",
          country: "France",
          country_code: "FR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 45.839911,
          longitude: 6.211234,
          timezone: "Europe/Paris",
          wikipedia: "https://fr.wikipedia.org/wiki/Talloires-Montmin",
        },
      },
      {
        id: "1229966466",
        status: "active",
        title: "Sandane",
        location: {
          city: "Sandane",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 61.766667,
          longitude: 6.216667,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1499022660",
        status: "active",
        title: "Agua de Pena: Machico, Madeira",
        location: {
          city: "Agua de Pena",
          region: "Autonomous Region of Madeira",
          region_code: "KbgeWgeW",
          country: "Portugal",
          country_code: "PT",
          continent: "Europe",
          continent_code: "EU",
          latitude: 32.717463,
          longitude: -16.766413,
          timezone: "Atlantic/Madeira",
          wikipedia: "https://pt.wikipedia.org/wiki/Água de Pena",
        },
      },
      {
        id: "1476394068",
        status: "active",
        title: "Elbrus: Mount - Kabardino-Balkariya",
        location: {
          city: "Elbrus",
          region: "Kabardino-Balkaria",
          region_code: "RU.22",
          country: "Russia",
          country_code: "RU",
          continent: "Europe",
          continent_code: "EU",
          latitude: 43.30441,
          longitude: 42.460129,
          timezone: "Europe/Moscow",
          wikipedia: "",
        },
      },
      {
        id: "1040549429",
        status: "active",
        title: "Alt St. Johann: Chäserrugg",
        location: {
          city: "Alt St. Johann",
          region: "Canton of St. Gallen",
          region_code: "CH.SG",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 47.155297,
          longitude: 9.313016,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Alt St. Johann",
        },
      },
      {
        id: "1196582275",
        status: "active",
        title: "Ernen: Mühlebach",
        location: {
          city: "Ernen",
          region: "Valais",
          region_code: "CH.VS",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.408082,
          longitude: 8.158207,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Ernen",
        },
      },
      {
        id: "1521534041",
        status: "active",
        title: "la Coma i la Pedra: Port Del Comte",
        location: {
          city: "la Coma i la Pedra",
          region: "Catalonia",
          region_code: "ES.56",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 42.172356,
          longitude: 1.563256,
          timezone: "Europe/Madrid",
          wikipedia: "https://ca.wikipedia.org/wiki/La Coma i la Pedra",
        },
      },
      {
        id: "1436977359",
        status: "active",
        title: "Diggle › South-East: Running Hill Lane",
        location: {
          city: "Diggle",
          region: "England",
          region_code: "GB.ENG",
          country: "United Kingdom",
          country_code: "GB",
          continent: "Europe",
          continent_code: "EU",
          latitude: 53.56744,
          longitude: -1.99723,
          timezone: "Europe/London",
          wikipedia: "",
        },
      },
      {
        id: "1458250522",
        status: "active",
        title:
          "Lajes do Pico › West: Casa do Flores - Lajes Do Pico - Espaço Talassa - Mount Pico",
        location: {
          city: "Lajes do Pico",
          region: "Azores",
          region_code: "PT.23",
          country: "Portugal",
          country_code: "PT",
          continent: "Europe",
          continent_code: "EU",
          latitude: 38.397881,
          longitude: -28.251815,
          timezone: "Atlantic/Azores",
          wikipedia: "https://pt.wikipedia.org/wiki/Lajes do Pico (freguesia)",
        },
      },
      {
        id: "1587640606",
        status: "active",
        title: "Møre og Romsdal: Arena Overøye Stordal Alpine Center",
        location: {
          city: "Møre og Romsdal",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 62.40885,
          longitude: 7.212218,
          timezone: "Europe/Oslo",
          wikipedia: "https://no.wikipedia.org/wiki/Møre og Romsdal",
        },
      },
      {
        id: "1068223161",
        status: "active",
        title: "Adelboden: Engstligenalp bei",
        location: {
          city: "Adelboden",
          region: "Bern",
          region_code: "CH.BE",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.445092,
          longitude: 7.563958,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Adelboden",
        },
      },
      {
        id: "1576343988",
        status: "active",
        title: "Setcases",
        location: {
          city: "Setcases",
          region: "Catalonia",
          region_code: "ES.56",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 42.375484,
          longitude: 2.301336,
          timezone: "Europe/Madrid",
          wikipedia: "https://ca.wikipedia.org/wiki/Setcases",
        },
      },
      {
        id: "1499097969",
        status: "active",
        title: "Karpathos › North-East: Bay Watch - ALIMOUNDA MARE 5* Hotel",
        location: {
          city: "Karpathos",
          region: "Aegean",
          region_code: "GR.ESYE41",
          country: "Greece",
          country_code: "GR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 35.52083,
          longitude: 27.2099,
          timezone: "Europe/Athens",
          wikipedia: "https://de.wikipedia.org/wiki/Karpathos (Stadt)",
        },
      },
      {
        id: "1550077182",
        status: "active",
        title: "Santa Barbara County: Channel Islands",
        location: {
          city: "Santa Barbara County",
          region: "Santa Barbara County",
          region_code: "",
          country: "United States",
          country_code: "US",
          continent: "North America",
          continent_code: "NA",
          latitude: 34.029176,
          longitude: -119.784456,
          timezone: "America/Los_Angeles",
          wikipedia:
            "https://en.wikipedia.org/wiki/Santa Barbara County, California",
        },
      },
      {
        id: "1242521789",
        status: "active",
        title: "Navia: playa de",
        location: {
          city: "Navia",
          region: "Asturias",
          region_code: "ES.34",
          country: "Spain",
          country_code: "ES",
          continent: "Europe",
          continent_code: "EU",
          latitude: 43.548533,
          longitude: -6.719084,
          timezone: "Europe/Madrid",
          wikipedia: "https://es.wikipedia.org/wiki/Navia (Asturias)",
        },
      },
      {
        id: "1294394283",
        status: "active",
        title: "Saint-Jean-de-Sixt: Mont Durand",
        location: {
          city: "Saint-Jean-de-Sixt",
          region: "Auvergne-Rhone-Alpes",
          region_code: "FR.84",
          country: "France",
          country_code: "FR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 45.919243,
          longitude: 6.420265,
          timezone: "Europe/Paris",
          wikipedia: "https://fr.wikipedia.org/wiki/Saint-Jean-de-Sixt",
        },
      },
      {
        id: "1574201349",
        status: "active",
        title: "Sinnes: Ålsheii - Vest-Agder - climbing park",
        location: {
          city: "Sinnes",
          region: null,
          region_code: null,
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 58.909085,
          longitude: 6.836684,
          timezone: "Europe/Oslo",
          wikipedia: "https://no.wikipedia.org/wiki/Sinnes",
        },
      },
      {
        id: "1222279962",
        status: "active",
        title:
          "Ravoire: Vue sur la route du Col de la Forclaz sur Martigny Valais Suisse",
        location: {
          city: "Ravoire",
          region: "Auvergne-Rhone-Alpes",
          region_code: "FR.84",
          country: "France",
          country_code: "FR",
          continent: "Europe",
          continent_code: "EU",
          latitude: 46.10016,
          longitude: 7.05782,
          timezone: "Europe/Zurich",
          wikipedia: "",
        },
      },
      {
        id: "1496052826",
        status: "active",
        title: "Valldal: Norddal - Eidsdal - Tafjorden - Norddalsfjorden",
        location: {
          city: "Valldal",
          region: "Møre og Romsdal",
          region_code: "KgIjbjb",
          country: "Norway",
          country_code: "NO",
          continent: "Europe",
          continent_code: "EU",
          latitude: 62.29782,
          longitude: 7.26374,
          timezone: "Europe/Oslo",
          wikipedia: "",
        },
      },
      {
        id: "1230893951",
        status: "active",
        title:
          "Mollis: Naturfreundehaus Fronalp, Skigebiet Schilt oberhalb - Glarnerland",
        location: {
          city: "Mollis",
          region: "Canton of Glarus",
          region_code: "CH.GL",
          country: "Switzerland",
          country_code: "CH",
          continent: "Europe",
          continent_code: "EU",
          latitude: 47.073051,
          longitude: 9.092302,
          timezone: "Europe/Zurich",
          wikipedia: "https://de.wikipedia.org/wiki/Mollis",
        },
      },
      {
        id: "1515775649",
        status: "active",
        title: "Gemeinde Tux › South-East: Eggalm Bahnen",
        location: {
          city: "Gemeinde Tux",
          region: "Tyrol",
          region_code: "AT.07",
          country: "Austria",
          country_code: "AT",
          continent: "Europe",
          continent_code: "EU",
          latitude: 47.164299,
          longitude: 11.70286,
          timezone: "Europe/Vienna",
          wikipedia: "https://de.wikipedia.org/wiki/Tux (Tirol)",
        },
      },
    ],
  },
};
