export const parks = {
	status: "OK",
	result: {
		offset: 0,
		limit: 50,
		total: 22,
		webcams: [
			{
				id: "1496254676",
				status: "active",
				title: "Forte dei Marmi: Piazza Navari (Pontile)°",
				location: {
					city: "Forte dei Marmi",
					region: "Tuscany",
					region_code: "IT.16",
					country: "Italy",
					country_code: "IT",
					continent: "Europe",
					continent_code: "EU",
					latitude: 43.957705,
					longitude: 10.166899,
					timezone: "Europe/Rome",
					wikipedia: "https://it.wikipedia.org/wiki/Forte dei Marmi",
				},
			},
			{
				id: "1541698349",
				status: "active",
				title: "ˈpæɹ.ɪs: 16th arrondissement - Bois de Boulogne - Paris La Défense - Paris",
				location: {
					city: "ˈpæɹ.ɪs",
					region: "Ile-de-France",
					region_code: "FR.11",
					country: "France",
					country_code: "FR",
					continent: "Europe",
					continent_code: "EU",
					latitude: 48.867189,
					longitude: 2.272416,
					timezone: "Europe/Paris",
					wikipedia: "https://fr.wikipedia.org/wiki/Paris",
				},
			},
			{
				id: "1436618683",
				status: "active",
				title: "Chernihiv › East",
				location: {
					city: "Chernihiv",
					region: "Chernihiv Oblast",
					region_code: "UA.02",
					country: "Ukraine",
					country_code: "UA",
					continent: "Europe",
					continent_code: "EU",
					latitude: 51.498795,
					longitude: 31.276118,
					timezone: "Europe/Kiev",
					wikipedia: "https://uk.wikipedia.org/wiki/Чернігів",
				},
			},
			{
				id: "1453251896",
				status: "active",
				title: "Yuzhno-Sakhalinsk › South: Park im. Yu.A. Gagarina",
				location: {
					city: "Yuzhno-Sakhalinsk",
					region: "Sakhalin Oblast",
					region_code: "RU.64",
					country: "Russia",
					country_code: "RU",
					continent: "Europe",
					continent_code: "EU",
					latitude: 46.966989,
					longitude: 142.753963,
					timezone: "Asia/Sakhalin",
					wikipedia: "",
				},
			},
			{
				id: "1521205329",
				status: "active",
				title: "Estepona: El Paraiso Golf Club",
				location: {
					city: "Estepona",
					region: "Andalusia",
					region_code: "ES.51",
					country: "Spain",
					country_code: "ES",
					continent: "Europe",
					continent_code: "EU",
					latitude: 36.47796,
					longitude: -5.03378,
					timezone: "Europe/Madrid",
					wikipedia: "https://es.wikipedia.org/wiki/Estepona",
				},
			},
			{
				id: "1581016646",
				status: "active",
				title: "Gisborne › East",
				location: {
					city: "Gisborne",
					region: "Gisborne",
					region_code: "NZ.F1",
					country: "New Zealand",
					country_code: "NZ",
					continent: "Oceania",
					continent_code: "OC",
					latitude: -38.671673,
					longitude: 178.018619,
					timezone: "Pacific/Auckland",
					wikipedia: "https://en.wikipedia.org/wiki/Gisborne, New Zealand",
				},
			},
			{
				id: "1451723021",
				status: "active",
				title: "District of Prešov › South-East: Hlavná - Client Center of the Municipality of Prešov",
				location: {
					city: "District of Prešov",
					region: "Region of Prešov",
					region_code: "SK.05",
					country: "Slovakia",
					country_code: "SK",
					continent: "Europe",
					continent_code: "EU",
					latitude: 48.997306,
					longitude: 21.239965,
					timezone: "Europe/Bratislava",
					wikipedia: "https://sk.wikipedia.org/wiki/Prešov (okres)",
				},
			},
			{
				id: "1457347572",
				status: "active",
				title: "Wisla: Wisła",
				location: {
					city: "Wisla",
					region: "Silesian Voivodeship",
					region_code: "PL.83",
					country: "Poland",
					country_code: "PL",
					continent: "Europe",
					continent_code: "EU",
					latitude: 49.654853,
					longitude: 18.859119,
					timezone: "Europe/Warsaw",
					wikipedia: "https://pl.wikipedia.org/wiki/Wisła (miasto)",
				},
			},
			{
				id: "1242829621",
				status: "active",
				title: "Bad Wildbad",
				location: {
					city: "Bad Wildbad",
					region: "Baden-Württemberg",
					region_code: "DE.01",
					country: "Germany",
					country_code: "DE",
					continent: "Europe",
					continent_code: "EU",
					latitude: 48.74915,
					longitude: 8.550721,
					timezone: "Europe/Berlin",
					wikipedia: "https://de.wikipedia.org/wiki/Bad Wildbad",
				},
			},
			{
				id: "1454271431",
				status: "active",
				title: "Primorsko › South",
				location: {
					city: "Primorsko",
					region: "Burgas",
					region_code: "BG.39",
					country: "Bulgaria",
					country_code: "BG",
					continent: "Europe",
					continent_code: "EU",
					latitude: 42.267909,
					longitude: 27.753525,
					timezone: "Europe/Sofia",
					wikipedia: "https://bg.wikipedia.org/wiki/Приморско",
				},
			},
			{
				id: "1517128695",
				status: "active",
				title: "Antigua Guatemala: Finca DeFay (Château et vignoble DeFay)",
				location: {
					city: "Antigua Guatemala",
					region: "Sacatepequez",
					region_code: "GT.16",
					country: "Guatemala",
					country_code: "GT",
					continent: "North America",
					continent_code: "NA",
					latitude: 14.458866,
					longitude: -90.688405,
					timezone: "America/Guatemala",
					wikipedia: "https://es.wikipedia.org/wiki/Antigua Guatemala",
				},
			},
			{
				id: "1520075126",
				status: "active",
				title: "Netishyn: Khmelnytskyi",
				location: {
					city: "Netishyn",
					region: "Khmelnytskyi Oblast",
					region_code: "UA.09",
					country: "Ukraine",
					country_code: "UA",
					continent: "Europe",
					continent_code: "EU",
					latitude: 50.328579,
					longitude: 26.648684,
					timezone: "Europe/Kiev",
					wikipedia: "https://uk.wikipedia.org/wiki/Нетішин",
				},
			},
			{
				id: "1438529610",
				status: "active",
				title: "Selston › West: Codnor Park - Ripley - Amber Valley District",
				location: {
					city: "Selston",
					region: "England",
					region_code: "GB.ENG",
					country: "United Kingdom",
					country_code: "GB",
					continent: "Europe",
					continent_code: "EU",
					latitude: 53.071212,
					longitude: -1.293297,
					timezone: "Europe/London",
					wikipedia: "",
				},
			},
			{
				id: "1519797614",
				status: "active",
				title: "Caracal › South-West: Primăria Caracal",
				location: {
					city: "Caracal",
					region: null,
					region_code: null,
					country: "Romania",
					country_code: "RO",
					continent: "Europe",
					continent_code: "EU",
					latitude: 44.111625,
					longitude: 24.345843,
					timezone: "Europe/Bucharest",
					wikipedia: "",
				},
			},
			{
				id: "1500362993",
				status: "active",
				title: "Zrenjanin: City central park",
				location: {
					city: "Zrenjanin",
					region: "Vojvodina",
					region_code: "RS.VO",
					country: "Serbia",
					country_code: "RS",
					continent: "Europe",
					continent_code: "EU",
					latitude: 45.380871,
					longitude: 20.389498,
					timezone: "Europe/Belgrade",
					wikipedia: "https://sr.wikipedia.org/wiki/Зрењанин",
				},
			},
			{
				id: "1587891582",
				status: "active",
				title: "Sylt › South-East: Morsum",
				location: {
					city: "Sylt",
					region: "Schleswig-Holstein",
					region_code: "DE.10",
					country: "Germany",
					country_code: "DE",
					continent: "Europe",
					continent_code: "EU",
					latitude: 54.873471,
					longitude: 8.459343,
					timezone: "Europe/Berlin",
					wikipedia: "https://de.wikipedia.org/wiki/Sylt (Gemeinde)",
				},
			},
			{
				id: "1456735376",
				status: "active",
				title: "Primorsko › West",
				location: {
					city: "Primorsko",
					region: "Burgas",
					region_code: "BG.39",
					country: "Bulgaria",
					country_code: "BG",
					continent: "Europe",
					continent_code: "EU",
					latitude: 42.266901,
					longitude: 27.754233,
					timezone: "Europe/Sofia",
					wikipedia: "https://bg.wikipedia.org/wiki/Приморско",
				},
			},
			{
				id: "1510301402",
				status: "active",
				title: "Calgary: Central Memorial Park",
				location: {
					city: "Calgary",
					region: "Alberta",
					region_code: "CA.01",
					country: "Canada",
					country_code: "CA",
					continent: "North America",
					continent_code: "NA",
					latitude: 51.040652,
					longitude: -114.070216,
					timezone: "America/Edmonton",
					wikipedia: "",
				},
			},
			{
				id: "1414340840",
				status: "active",
				title: "Portage: Purdue Research Foundation",
				location: {
					city: "Portage",
					region: "Indiana",
					region_code: "US.IN",
					country: "United States",
					country_code: "US",
					continent: "North America",
					continent_code: "NA",
					latitude: 41.483328,
					longitude: -87.18338,
					timezone: "America/Chicago",
					wikipedia: "https://en.wikipedia.org/wiki/Portage, Indiana",
				},
			},
			{
				id: "1416931013",
				status: "active",
				title: "Rochester: Monroe Community College",
				location: {
					city: "Rochester",
					region: "New York",
					region_code: "US.NY",
					country: "United States",
					country_code: "US",
					continent: "North America",
					continent_code: "NA",
					latitude: 43.10117,
					longitude: -77.61,
					timezone: "America/New_York",
					wikipedia: "https://en.wikipedia.org/wiki/Rochester, New York",
				},
			},
			{
				id: "1512425466",
				status: "active",
				title: "Bad Rappenau: Salinen Park",
				location: {
					city: "Bad Rappenau",
					region: "Baden-Württemberg",
					region_code: "DE.01",
					country: "Germany",
					country_code: "DE",
					continent: "Europe",
					continent_code: "EU",
					latitude: 49.237653,
					longitude: 9.117263,
					timezone: "Europe/Berlin",
					wikipedia: "https://de.wikipedia.org/wiki/Bad Rappenau",
				},
			},
			{
				id: "1516260413",
				status: "active",
				title: "Chotebor › East: Chotěboř - Kraj Vysočina, Česko",
				location: {
					city: "Chotebor",
					region: "Southeast",
					region_code: "CZ.78",
					country: "Czechia",
					country_code: "CZ",
					continent: "Europe",
					continent_code: "EU",
					latitude: 49.72072,
					longitude: 15.67018,
					timezone: "Europe/Prague",
					wikipedia: "https://cs.wikipedia.org/wiki/Chotěboř",
				},
			},
		],
	},
};
